plugins {
    id 'fabric-loom' version '1.10.3'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_name
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You need only look here to add any special repositories for your dependencies
}

dependencies {
    // To change the versions please see the gradle.gradle file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is really just a convenience helper mod,
    // everything else in there can be done with installed network
    // providers and their own chosen dependency managers
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

apply from: 'gradle.properties'

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}
