/*
 * Decompiled with CFR 0.152.
 */
package net.minecraft.world.entity;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.EntityType;

public class EntityTypeIds {
    public static final ResourceKey<EntityType<?>> ACACIA_BOAT = EntityTypeIds.create("acacia_boat");
    public static final ResourceKey<EntityType<?>> ACACIA_CHEST_BOAT = EntityTypeIds.create("acacia_chest_boat");
    public static final ResourceKey<EntityType<?>> ALLAY = EntityTypeIds.create("allay");
    public static final ResourceKey<EntityType<?>> AREA_EFFECT_CLOUD = EntityTypeIds.create("area_effect_cloud");
    public static final ResourceKey<EntityType<?>> ARMADILLO = EntityTypeIds.create("armadillo");
    public static final ResourceKey<EntityType<?>> ARMOR_STAND = EntityTypeIds.create("armor_stand");
    public static final ResourceKey<EntityType<?>> ARROW = EntityTypeIds.create("arrow");
    public static final ResourceKey<EntityType<?>> AXOLOTL = EntityTypeIds.create("axolotl");
    public static final ResourceKey<EntityType<?>> BAMBOO_CHEST_RAFT = EntityTypeIds.create("bamboo_chest_raft");
    public static final ResourceKey<EntityType<?>> BAMBOO_RAFT = EntityTypeIds.create("bamboo_raft");
    public static final ResourceKey<EntityType<?>> BAT = EntityTypeIds.create("bat");
    public static final ResourceKey<EntityType<?>> BEE = EntityTypeIds.create("bee");
    public static final ResourceKey<EntityType<?>> BIRCH_BOAT = EntityTypeIds.create("birch_boat");
    public static final ResourceKey<EntityType<?>> BIRCH_CHEST_BOAT = EntityTypeIds.create("birch_chest_boat");
    public static final ResourceKey<EntityType<?>> BLAZE = EntityTypeIds.create("blaze");
    public static final ResourceKey<EntityType<?>> BLOCK_DISPLAY = EntityTypeIds.create("block_display");
    public static final ResourceKey<EntityType<?>> BOGGED = EntityTypeIds.create("bogged");
    public static final ResourceKey<EntityType<?>> BREEZE = EntityTypeIds.create("breeze");
    public static final ResourceKey<EntityType<?>> BREEZE_WIND_CHARGE = EntityTypeIds.create("breeze_wind_charge");
    public static final ResourceKey<EntityType<?>> CAMEL = EntityTypeIds.create("camel");
    public static final ResourceKey<EntityType<?>> CAMEL_HUSK = EntityTypeIds.create("camel_husk");
    public static final ResourceKey<EntityType<?>> CAT = EntityTypeIds.create("cat");
    public static final ResourceKey<EntityType<?>> CAVE_SPIDER = EntityTypeIds.create("cave_spider");
    public static final ResourceKey<EntityType<?>> CHERRY_BOAT = EntityTypeIds.create("cherry_boat");
    public static final ResourceKey<EntityType<?>> CHERRY_CHEST_BOAT = EntityTypeIds.create("cherry_chest_boat");
    public static final ResourceKey<EntityType<?>> CHEST_MINECART = EntityTypeIds.create("chest_minecart");
    public static final ResourceKey<EntityType<?>> CHICKEN = EntityTypeIds.create("chicken");
    public static final ResourceKey<EntityType<?>> COD = EntityTypeIds.create("cod");
    public static final ResourceKey<EntityType<?>> COPPER_GOLEM = EntityTypeIds.create("copper_golem");
    public static final ResourceKey<EntityType<?>> COMMAND_BLOCK_MINECART = EntityTypeIds.create("command_block_minecart");
    public static final ResourceKey<EntityType<?>> COW = EntityTypeIds.create("cow");
    public static final ResourceKey<EntityType<?>> CREAKING = EntityTypeIds.create("creaking");
    public static final ResourceKey<EntityType<?>> CREEPER = EntityTypeIds.create("creeper");
    public static final ResourceKey<EntityType<?>> DARK_OAK_BOAT = EntityTypeIds.create("dark_oak_boat");
    public static final ResourceKey<EntityType<?>> DARK_OAK_CHEST_BOAT = EntityTypeIds.create("dark_oak_chest_boat");
    public static final ResourceKey<EntityType<?>> DOLPHIN = EntityTypeIds.create("dolphin");
    public static final ResourceKey<EntityType<?>> DONKEY = EntityTypeIds.create("donkey");
    public static final ResourceKey<EntityType<?>> DRAGON_FIREBALL = EntityTypeIds.create("dragon_fireball");
    public static final ResourceKey<EntityType<?>> DROWNED = EntityTypeIds.create("drowned");
    public static final ResourceKey<EntityType<?>> EGG = EntityTypeIds.create("egg");
    public static final ResourceKey<EntityType<?>> ELDER_GUARDIAN = EntityTypeIds.create("elder_guardian");
    public static final ResourceKey<EntityType<?>> ENDERMAN = EntityTypeIds.create("enderman");
    public static final ResourceKey<EntityType<?>> ENDERMITE = EntityTypeIds.create("endermite");
    public static final ResourceKey<EntityType<?>> ENDER_DRAGON = EntityTypeIds.create("ender_dragon");
    public static final ResourceKey<EntityType<?>> ENDER_PEARL = EntityTypeIds.create("ender_pearl");
    public static final ResourceKey<EntityType<?>> END_CRYSTAL = EntityTypeIds.create("end_crystal");
    public static final ResourceKey<EntityType<?>> EVOKER = EntityTypeIds.create("evoker");
    public static final ResourceKey<EntityType<?>> EVOKER_FANGS = EntityTypeIds.create("evoker_fangs");
    public static final ResourceKey<EntityType<?>> EXPERIENCE_BOTTLE = EntityTypeIds.create("experience_bottle");
    public static final ResourceKey<EntityType<?>> EXPERIENCE_ORB = EntityTypeIds.create("experience_orb");
    public static final ResourceKey<EntityType<?>> EYE_OF_ENDER = EntityTypeIds.create("eye_of_ender");
    public static final ResourceKey<EntityType<?>> FALLING_BLOCK = EntityTypeIds.create("falling_block");
    public static final ResourceKey<EntityType<?>> FIREBALL = EntityTypeIds.create("fireball");
    public static final ResourceKey<EntityType<?>> FIREWORK_ROCKET = EntityTypeIds.create("firework_rocket");
    public static final ResourceKey<EntityType<?>> FOX = EntityTypeIds.create("fox");
    public static final ResourceKey<EntityType<?>> FROG = EntityTypeIds.create("frog");
    public static final ResourceKey<EntityType<?>> FURNACE_MINECART = EntityTypeIds.create("furnace_minecart");
    public static final ResourceKey<EntityType<?>> GHAST = EntityTypeIds.create("ghast");
    public static final ResourceKey<EntityType<?>> HAPPY_GHAST = EntityTypeIds.create("happy_ghast");
    public static final ResourceKey<EntityType<?>> GIANT = EntityTypeIds.create("giant");
    public static final ResourceKey<EntityType<?>> GLOW_ITEM_FRAME = EntityTypeIds.create("glow_item_frame");
    public static final ResourceKey<EntityType<?>> GLOW_SQUID = EntityTypeIds.create("glow_squid");
    public static final ResourceKey<EntityType<?>> GOAT = EntityTypeIds.create("goat");
    public static final ResourceKey<EntityType<?>> GUARDIAN = EntityTypeIds.create("guardian");
    public static final ResourceKey<EntityType<?>> HOGLIN = EntityTypeIds.create("hoglin");
    public static final ResourceKey<EntityType<?>> HOPPER_MINECART = EntityTypeIds.create("hopper_minecart");
    public static final ResourceKey<EntityType<?>> HORSE = EntityTypeIds.create("horse");
    public static final ResourceKey<EntityType<?>> HUSK = EntityTypeIds.create("husk");
    public static final ResourceKey<EntityType<?>> ILLUSIONER = EntityTypeIds.create("illusioner");
    public static final ResourceKey<EntityType<?>> INTERACTION = EntityTypeIds.create("interaction");
    public static final ResourceKey<EntityType<?>> IRON_GOLEM = EntityTypeIds.create("iron_golem");
    public static final ResourceKey<EntityType<?>> ITEM = EntityTypeIds.create("item");
    public static final ResourceKey<EntityType<?>> ITEM_DISPLAY = EntityTypeIds.create("item_display");
    public static final ResourceKey<EntityType<?>> ITEM_FRAME = EntityTypeIds.create("item_frame");
    public static final ResourceKey<EntityType<?>> JUNGLE_BOAT = EntityTypeIds.create("jungle_boat");
    public static final ResourceKey<EntityType<?>> JUNGLE_CHEST_BOAT = EntityTypeIds.create("jungle_chest_boat");
    public static final ResourceKey<EntityType<?>> LEASH_KNOT = EntityTypeIds.create("leash_knot");
    public static final ResourceKey<EntityType<?>> LIGHTNING_BOLT = EntityTypeIds.create("lightning_bolt");
    public static final ResourceKey<EntityType<?>> LLAMA = EntityTypeIds.create("llama");
    public static final ResourceKey<EntityType<?>> LLAMA_SPIT = EntityTypeIds.create("llama_spit");
    public static final ResourceKey<EntityType<?>> MAGMA_CUBE = EntityTypeIds.create("magma_cube");
    public static final ResourceKey<EntityType<?>> MANGROVE_BOAT = EntityTypeIds.create("mangrove_boat");
    public static final ResourceKey<EntityType<?>> MANGROVE_CHEST_BOAT = EntityTypeIds.create("mangrove_chest_boat");
    public static final ResourceKey<EntityType<?>> MANNEQUIN = EntityTypeIds.create("mannequin");
    public static final ResourceKey<EntityType<?>> MARKER = EntityTypeIds.create("marker");
    public static final ResourceKey<EntityType<?>> MINECART = EntityTypeIds.create("minecart");
    public static final ResourceKey<EntityType<?>> MOOSHROOM = EntityTypeIds.create("mooshroom");
    public static final ResourceKey<EntityType<?>> MULE = EntityTypeIds.create("mule");
    public static final ResourceKey<EntityType<?>> NAUTILUS = EntityTypeIds.create("nautilus");
    public static final ResourceKey<EntityType<?>> OAK_BOAT = EntityTypeIds.create("oak_boat");
    public static final ResourceKey<EntityType<?>> OAK_CHEST_BOAT = EntityTypeIds.create("oak_chest_boat");
    public static final ResourceKey<EntityType<?>> OCELOT = EntityTypeIds.create("ocelot");
    public static final ResourceKey<EntityType<?>> OMINOUS_ITEM_SPAWNER = EntityTypeIds.create("ominous_item_spawner");
    public static final ResourceKey<EntityType<?>> PAINTING = EntityTypeIds.create("painting");
    public static final ResourceKey<EntityType<?>> PALE_OAK_BOAT = EntityTypeIds.create("pale_oak_boat");
    public static final ResourceKey<EntityType<?>> PALE_OAK_CHEST_BOAT = EntityTypeIds.create("pale_oak_chest_boat");
    public static final ResourceKey<EntityType<?>> PANDA = EntityTypeIds.create("panda");
    public static final ResourceKey<EntityType<?>> PARCHED = EntityTypeIds.create("parched");
    public static final ResourceKey<EntityType<?>> PARROT = EntityTypeIds.create("parrot");
    public static final ResourceKey<EntityType<?>> PHANTOM = EntityTypeIds.create("phantom");
    public static final ResourceKey<EntityType<?>> PIG = EntityTypeIds.create("pig");
    public static final ResourceKey<EntityType<?>> PIGLIN = EntityTypeIds.create("piglin");
    public static final ResourceKey<EntityType<?>> PIGLIN_BRUTE = EntityTypeIds.create("piglin_brute");
    public static final ResourceKey<EntityType<?>> PILLAGER = EntityTypeIds.create("pillager");
    public static final ResourceKey<EntityType<?>> POLAR_BEAR = EntityTypeIds.create("polar_bear");
    public static final ResourceKey<EntityType<?>> SPLASH_POTION = EntityTypeIds.create("splash_potion");
    public static final ResourceKey<EntityType<?>> LINGERING_POTION = EntityTypeIds.create("lingering_potion");
    public static final ResourceKey<EntityType<?>> PUFFERFISH = EntityTypeIds.create("pufferfish");
    public static final ResourceKey<EntityType<?>> RABBIT = EntityTypeIds.create("rabbit");
    public static final ResourceKey<EntityType<?>> RAVAGER = EntityTypeIds.create("ravager");
    public static final ResourceKey<EntityType<?>> SALMON = EntityTypeIds.create("salmon");
    public static final ResourceKey<EntityType<?>> SHEEP = EntityTypeIds.create("sheep");
    public static final ResourceKey<EntityType<?>> SHULKER = EntityTypeIds.create("shulker");
    public static final ResourceKey<EntityType<?>> SHULKER_BULLET = EntityTypeIds.create("shulker_bullet");
    public static final ResourceKey<EntityType<?>> SILVERFISH = EntityTypeIds.create("silverfish");
    public static final ResourceKey<EntityType<?>> SKELETON = EntityTypeIds.create("skeleton");
    public static final ResourceKey<EntityType<?>> SKELETON_HORSE = EntityTypeIds.create("skeleton_horse");
    public static final ResourceKey<EntityType<?>> SLIME = EntityTypeIds.create("slime");
    public static final ResourceKey<EntityType<?>> SMALL_FIREBALL = EntityTypeIds.create("small_fireball");
    public static final ResourceKey<EntityType<?>> SNIFFER = EntityTypeIds.create("sniffer");
    public static final ResourceKey<EntityType<?>> SNOWBALL = EntityTypeIds.create("snowball");
    public static final ResourceKey<EntityType<?>> SNOW_GOLEM = EntityTypeIds.create("snow_golem");
    public static final ResourceKey<EntityType<?>> SPAWNER_MINECART = EntityTypeIds.create("spawner_minecart");
    public static final ResourceKey<EntityType<?>> SPECTRAL_ARROW = EntityTypeIds.create("spectral_arrow");
    public static final ResourceKey<EntityType<?>> SPIDER = EntityTypeIds.create("spider");
    public static final ResourceKey<EntityType<?>> SPRUCE_BOAT = EntityTypeIds.create("spruce_boat");
    public static final ResourceKey<EntityType<?>> SPRUCE_CHEST_BOAT = EntityTypeIds.create("spruce_chest_boat");
    public static final ResourceKey<EntityType<?>> SQUID = EntityTypeIds.create("squid");
    public static final ResourceKey<EntityType<?>> STRAY = EntityTypeIds.create("stray");
    public static final ResourceKey<EntityType<?>> STRIDER = EntityTypeIds.create("strider");
    public static final ResourceKey<EntityType<?>> SULFUR_CUBE = EntityTypeIds.create("sulfur_cube");
    public static final ResourceKey<EntityType<?>> TADPOLE = EntityTypeIds.create("tadpole");
    public static final ResourceKey<EntityType<?>> TEXT_DISPLAY = EntityTypeIds.create("text_display");
    public static final ResourceKey<EntityType<?>> TNT = EntityTypeIds.create("tnt");
    public static final ResourceKey<EntityType<?>> TNT_MINECART = EntityTypeIds.create("tnt_minecart");
    public static final ResourceKey<EntityType<?>> TRADER_LLAMA = EntityTypeIds.create("trader_llama");
    public static final ResourceKey<EntityType<?>> TRIDENT = EntityTypeIds.create("trident");
    public static final ResourceKey<EntityType<?>> TROPICAL_FISH = EntityTypeIds.create("tropical_fish");
    public static final ResourceKey<EntityType<?>> TURTLE = EntityTypeIds.create("turtle");
    public static final ResourceKey<EntityType<?>> VEX = EntityTypeIds.create("vex");
    public static final ResourceKey<EntityType<?>> VILLAGER = EntityTypeIds.create("villager");
    public static final ResourceKey<EntityType<?>> VINDICATOR = EntityTypeIds.create("vindicator");
    public static final ResourceKey<EntityType<?>> WANDERING_TRADER = EntityTypeIds.create("wandering_trader");
    public static final ResourceKey<EntityType<?>> WARDEN = EntityTypeIds.create("warden");
    public static final ResourceKey<EntityType<?>> WIND_CHARGE = EntityTypeIds.create("wind_charge");
    public static final ResourceKey<EntityType<?>> WITCH = EntityTypeIds.create("witch");
    public static final ResourceKey<EntityType<?>> WITHER = EntityTypeIds.create("wither");
    public static final ResourceKey<EntityType<?>> WITHER_SKELETON = EntityTypeIds.create("wither_skeleton");
    public static final ResourceKey<EntityType<?>> WITHER_SKULL = EntityTypeIds.create("wither_skull");
    public static final ResourceKey<EntityType<?>> WOLF = EntityTypeIds.create("wolf");
    public static final ResourceKey<EntityType<?>> ZOGLIN = EntityTypeIds.create("zoglin");
    public static final ResourceKey<EntityType<?>> ZOMBIE = EntityTypeIds.create("zombie");
    public static final ResourceKey<EntityType<?>> ZOMBIE_HORSE = EntityTypeIds.create("zombie_horse");
    public static final ResourceKey<EntityType<?>> ZOMBIE_NAUTILUS = EntityTypeIds.create("zombie_nautilus");
    public static final ResourceKey<EntityType<?>> ZOMBIE_VILLAGER = EntityTypeIds.create("zombie_villager");
    public static final ResourceKey<EntityType<?>> ZOMBIFIED_PIGLIN = EntityTypeIds.create("zombified_piglin");
    public static final ResourceKey<EntityType<?>> PLAYER = EntityTypeIds.create("player");
    public static final ResourceKey<EntityType<?>> FISHING_BOBBER = EntityTypeIds.create("fishing_bobber");

    private static ResourceKey<EntityType<?>> create(String name) {
        return ResourceKey.create(Registries.ENTITY_TYPE, Identifier.withDefaultNamespace(name));
    }
}

